/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProjectsProjectIdIndexRouteImport } from './routes/_authenticated/projects.$projectId/index'
import { Route as AuthenticatedProjectsProjectIdScreenplaysScreenplayIdRouteRouteImport } from './routes/_authenticated/projects.$projectId/screenplays.$screenplayId/route'
import { Route as AuthenticatedProjectsProjectIdScreenplaysScreenplayIdIndexRouteImport } from './routes/_authenticated/projects.$projectId/screenplays.$screenplayId/index'
import { Route as AuthenticatedProjectsProjectIdScreenplaysScreenplayIdBreakdownRouteImport } from './routes/_authenticated/projects.$projectId/screenplays.$screenplayId/breakdown'
import { Route as AuthenticatedProjectsProjectIdScreenplaysScreenplayIdNavigatorRouteImport } from './routes/_authenticated/projects.$projectId/screenplays.$screenplayId/navigator'
import { Route as AuthenticatedProjectsProjectIdScreenplaysScreenplayIdSceneRouteImport } from './routes/_authenticated/projects.$projectId/screenplays.$screenplayId/scene'
import { Route as AuthenticatedProjectsProjectIdScreenplaysScreenplayIdWriterRouteImport } from './routes/_authenticated/projects.$projectId/screenplays.$screenplayId/writer'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsProjectIdIndexRoute =
  AuthenticatedProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdScreenplaysScreenplayIdRouteRoute =
  AuthenticatedProjectsProjectIdScreenplaysScreenplayIdRouteRouteImport.update({
    id: '/projects/$projectId/screenplays/$screenplayId',
    path: '/projects/$projectId/screenplays/$screenplayId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdScreenplaysScreenplayIdIndexRoute =
  AuthenticatedProjectsProjectIdScreenplaysScreenplayIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthenticatedProjectsProjectIdScreenplaysScreenplayIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdScreenplaysScreenplayIdBreakdownRoute =
  AuthenticatedProjectsProjectIdScreenplaysScreenplayIdBreakdownRouteImport.update(
    {
      id: '/breakdown',
      path: '/breakdown',
      getParentRoute: () =>
        AuthenticatedProjectsProjectIdScreenplaysScreenplayIdRouteRoute,
    } as any,
  )
const AuthenticatedProjectsProjectIdScreenplaysScreenplayIdNavigatorRoute =
  AuthenticatedProjectsProjectIdScreenplaysScreenplayIdNavigatorRouteImport.update(
    {
      id: '/navigator',
      path: '/navigator',
      getParentRoute: () =>
        AuthenticatedProjectsProjectIdScreenplaysScreenplayIdRouteRoute,
    } as any,
  )
const AuthenticatedProjectsProjectIdScreenplaysScreenplayIdSceneRoute =
  AuthenticatedProjectsProjectIdScreenplaysScreenplayIdSceneRouteImport.update({
    id: '/scene',
    path: '/scene',
    getParentRoute: () =>
      AuthenticatedProjectsProjectIdScreenplaysScreenplayIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdScreenplaysScreenplayIdWriterRoute =
  AuthenticatedProjectsProjectIdScreenplaysScreenplayIdWriterRouteImport.update(
    {
      id: '/writer',
      path: '/writer',
      getParentRoute: () =>
        AuthenticatedProjectsProjectIdScreenplaysScreenplayIdRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/projects/$projectId/screenplays/$screenplayId': typeof AuthenticatedProjectsProjectIdScreenplaysScreenplayIdRouteRouteWithChildren
  '/projects/$projectId/screenplays/$screenplayId/breakdown': typeof AuthenticatedProjectsProjectIdScreenplaysScreenplayIdBreakdownRoute
  '/projects/$projectId/screenplays/$screenplayId/navigator': typeof AuthenticatedProjectsProjectIdScreenplaysScreenplayIdNavigatorRoute
  '/projects/$projectId/screenplays/$screenplayId/scene': typeof AuthenticatedProjectsProjectIdScreenplaysScreenplayIdSceneRoute
  '/projects/$projectId/screenplays/$screenplayId/writer': typeof AuthenticatedProjectsProjectIdScreenplaysScreenplayIdWriterRoute
  '/projects/$projectId/screenplays/$screenplayId/': typeof AuthenticatedProjectsProjectIdScreenplaysScreenplayIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof AuthenticatedIndexRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/projects/$projectId/screenplays/$screenplayId/breakdown': typeof AuthenticatedProjectsProjectIdScreenplaysScreenplayIdBreakdownRoute
  '/projects/$projectId/screenplays/$screenplayId/navigator': typeof AuthenticatedProjectsProjectIdScreenplaysScreenplayIdNavigatorRoute
  '/projects/$projectId/screenplays/$screenplayId/scene': typeof AuthenticatedProjectsProjectIdScreenplaysScreenplayIdSceneRoute
  '/projects/$projectId/screenplays/$screenplayId/writer': typeof AuthenticatedProjectsProjectIdScreenplaysScreenplayIdWriterRoute
  '/projects/$projectId/screenplays/$screenplayId': typeof AuthenticatedProjectsProjectIdScreenplaysScreenplayIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/_authenticated/projects/$projectId/screenplays/$screenplayId': typeof AuthenticatedProjectsProjectIdScreenplaysScreenplayIdRouteRouteWithChildren
  '/_authenticated/projects/$projectId/screenplays/$screenplayId/breakdown': typeof AuthenticatedProjectsProjectIdScreenplaysScreenplayIdBreakdownRoute
  '/_authenticated/projects/$projectId/screenplays/$screenplayId/navigator': typeof AuthenticatedProjectsProjectIdScreenplaysScreenplayIdNavigatorRoute
  '/_authenticated/projects/$projectId/screenplays/$screenplayId/scene': typeof AuthenticatedProjectsProjectIdScreenplaysScreenplayIdSceneRoute
  '/_authenticated/projects/$projectId/screenplays/$screenplayId/writer': typeof AuthenticatedProjectsProjectIdScreenplaysScreenplayIdWriterRoute
  '/_authenticated/projects/$projectId/screenplays/$screenplayId/': typeof AuthenticatedProjectsProjectIdScreenplaysScreenplayIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/projects/$projectId/'
    | '/projects/$projectId/screenplays/$screenplayId'
    | '/projects/$projectId/screenplays/$screenplayId/breakdown'
    | '/projects/$projectId/screenplays/$screenplayId/navigator'
    | '/projects/$projectId/screenplays/$screenplayId/scene'
    | '/projects/$projectId/screenplays/$screenplayId/writer'
    | '/projects/$projectId/screenplays/$screenplayId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/'
    | '/projects/$projectId'
    | '/projects/$projectId/screenplays/$screenplayId/breakdown'
    | '/projects/$projectId/screenplays/$screenplayId/navigator'
    | '/projects/$projectId/screenplays/$screenplayId/scene'
    | '/projects/$projectId/screenplays/$screenplayId/writer'
    | '/projects/$projectId/screenplays/$screenplayId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/'
    | '/_authenticated/projects/$projectId/'
    | '/_authenticated/projects/$projectId/screenplays/$screenplayId'
    | '/_authenticated/projects/$projectId/screenplays/$screenplayId/breakdown'
    | '/_authenticated/projects/$projectId/screenplays/$screenplayId/navigator'
    | '/_authenticated/projects/$projectId/screenplays/$screenplayId/scene'
    | '/_authenticated/projects/$projectId/screenplays/$screenplayId/writer'
    | '/_authenticated/projects/$projectId/screenplays/$screenplayId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/': {
      id: '/_authenticated/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/screenplays/$screenplayId': {
      id: '/_authenticated/projects/$projectId/screenplays/$screenplayId'
      path: '/projects/$projectId/screenplays/$screenplayId'
      fullPath: '/projects/$projectId/screenplays/$screenplayId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdScreenplaysScreenplayIdRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/screenplays/$screenplayId/': {
      id: '/_authenticated/projects/$projectId/screenplays/$screenplayId/'
      path: '/'
      fullPath: '/projects/$projectId/screenplays/$screenplayId/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdScreenplaysScreenplayIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdScreenplaysScreenplayIdRouteRoute
    }
    '/_authenticated/projects/$projectId/screenplays/$screenplayId/breakdown': {
      id: '/_authenticated/projects/$projectId/screenplays/$screenplayId/breakdown'
      path: '/breakdown'
      fullPath: '/projects/$projectId/screenplays/$screenplayId/breakdown'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdScreenplaysScreenplayIdBreakdownRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdScreenplaysScreenplayIdRouteRoute
    }
    '/_authenticated/projects/$projectId/screenplays/$screenplayId/navigator': {
      id: '/_authenticated/projects/$projectId/screenplays/$screenplayId/navigator'
      path: '/navigator'
      fullPath: '/projects/$projectId/screenplays/$screenplayId/navigator'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdScreenplaysScreenplayIdNavigatorRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdScreenplaysScreenplayIdRouteRoute
    }
    '/_authenticated/projects/$projectId/screenplays/$screenplayId/scene': {
      id: '/_authenticated/projects/$projectId/screenplays/$screenplayId/scene'
      path: '/scene'
      fullPath: '/projects/$projectId/screenplays/$screenplayId/scene'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdScreenplaysScreenplayIdSceneRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdScreenplaysScreenplayIdRouteRoute
    }
    '/_authenticated/projects/$projectId/screenplays/$screenplayId/writer': {
      id: '/_authenticated/projects/$projectId/screenplays/$screenplayId/writer'
      path: '/writer'
      fullPath: '/projects/$projectId/screenplays/$screenplayId/writer'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdScreenplaysScreenplayIdWriterRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdScreenplaysScreenplayIdRouteRoute
    }
  }
}

interface AuthenticatedProjectsProjectIdScreenplaysScreenplayIdRouteRouteChildren {
  AuthenticatedProjectsProjectIdScreenplaysScreenplayIdBreakdownRoute: typeof AuthenticatedProjectsProjectIdScreenplaysScreenplayIdBreakdownRoute
  AuthenticatedProjectsProjectIdScreenplaysScreenplayIdNavigatorRoute: typeof AuthenticatedProjectsProjectIdScreenplaysScreenplayIdNavigatorRoute
  AuthenticatedProjectsProjectIdScreenplaysScreenplayIdSceneRoute: typeof AuthenticatedProjectsProjectIdScreenplaysScreenplayIdSceneRoute
  AuthenticatedProjectsProjectIdScreenplaysScreenplayIdWriterRoute: typeof AuthenticatedProjectsProjectIdScreenplaysScreenplayIdWriterRoute
  AuthenticatedProjectsProjectIdScreenplaysScreenplayIdIndexRoute: typeof AuthenticatedProjectsProjectIdScreenplaysScreenplayIdIndexRoute
}

const AuthenticatedProjectsProjectIdScreenplaysScreenplayIdRouteRouteChildren: AuthenticatedProjectsProjectIdScreenplaysScreenplayIdRouteRouteChildren =
  {
    AuthenticatedProjectsProjectIdScreenplaysScreenplayIdBreakdownRoute:
      AuthenticatedProjectsProjectIdScreenplaysScreenplayIdBreakdownRoute,
    AuthenticatedProjectsProjectIdScreenplaysScreenplayIdNavigatorRoute:
      AuthenticatedProjectsProjectIdScreenplaysScreenplayIdNavigatorRoute,
    AuthenticatedProjectsProjectIdScreenplaysScreenplayIdSceneRoute:
      AuthenticatedProjectsProjectIdScreenplaysScreenplayIdSceneRoute,
    AuthenticatedProjectsProjectIdScreenplaysScreenplayIdWriterRoute:
      AuthenticatedProjectsProjectIdScreenplaysScreenplayIdWriterRoute,
    AuthenticatedProjectsProjectIdScreenplaysScreenplayIdIndexRoute:
      AuthenticatedProjectsProjectIdScreenplaysScreenplayIdIndexRoute,
  }

const AuthenticatedProjectsProjectIdScreenplaysScreenplayIdRouteRouteWithChildren =
  AuthenticatedProjectsProjectIdScreenplaysScreenplayIdRouteRoute._addFileChildren(
    AuthenticatedProjectsProjectIdScreenplaysScreenplayIdRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProjectsProjectIdIndexRoute: typeof AuthenticatedProjectsProjectIdIndexRoute
  AuthenticatedProjectsProjectIdScreenplaysScreenplayIdRouteRoute: typeof AuthenticatedProjectsProjectIdScreenplaysScreenplayIdRouteRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProjectsProjectIdIndexRoute:
    AuthenticatedProjectsProjectIdIndexRoute,
  AuthenticatedProjectsProjectIdScreenplaysScreenplayIdRouteRoute:
    AuthenticatedProjectsProjectIdScreenplaysScreenplayIdRouteRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
